-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 14:22:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mariscos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mariscos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mariscos` DEFAULT CHARACTER SET utf8 ;
USE `db_mariscos` ;


-- -----------------------------------------------------
-- Table `db_mariscos`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mariscos`.`users` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(450) DEFAULT NULL,
  `puesto` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_mariscos`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mariscos`.`auth` (
  `id` varchar(36) DEFAULT NULL,
  `email` varchar(450) DEFAULT NULL,
  `password` varchar(4500) DEFAULT NULL,
  KEY `fk_user_id_to_auth_id_idx` (`id`),
  CONSTRAINT `fk_user_id_to_auth_id` FOREIGN KEY (`id`) REFERENCES `users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_mariscos`.`lastSaleInserted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mariscos`.`lastSaleInserted` (
    `tableNumber` varchar(45) NOT NULL,
    `fecha` varchar(70) DEFAULT NULL,
    PRIMARY KEY (`tableNumber`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `db_mariscos`.`openTables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mariscos`.`openTables` (
    `tableNumber` varchar(45) NOT NULL,
    `fecha` varchar(70) DEFAULT NULL,
    `mesero` varchar(36) DEFAULT NULL,
    `order` json DEFAULT NULL,
    PRIMARY KEY (`tableNumber`),
    KEY `fk_user_id_to_mesero_idx` (`mesero`),
    CONSTRAINT `fk_user_id_to_mesero` FOREIGN KEY (`mesero`) REFERENCES `users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `db_mariscos`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mariscos`.`products` (
    `id` int NOT NULL AUTO_INCREMENT,
    `category` varchar(45) DEFAULT NULL,
    `price` decimal(10,2) DEFAULT NULL,
    `name` varchar(450) DEFAULT NULL,
    `item` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `db_mariscos`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mariscos`.`sales` (
    `id` int NOT NULL AUTO_INCREMENT,
    `tableNumber` varchar(45) DEFAULT NULL,
    `fecha` varchar(70) DEFAULT NULL,
    `products` json DEFAULT NULL,
    `mesero` varchar(36) DEFAULT NULL,
    `total` decimal(10,2) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_users_id_to_mesero_idx` (`mesero`),
    CONSTRAINT `fk_users_id_to_mesero` FOREIGN KEY (`mesero`) REFERENCES `users` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;